name: azure-app-to-get-image-details-from-acr
on:
  workflow_dispatch:

run-name: azure-app-to-get-image-details-from-acr
env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  azure-app-to-get-image-details-from-acr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish docker image with tag
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/azure-app-to-get-image-details-from-acr:latest

      - name: Completed
        run: |
          echo "program completed successfully"